apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/managed-by: epg-station
    app.kubernetes.io/name: epg-station
  name: epg-station-thumbnail
  namespace: epg-station
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
