apiVersion: apps/v1
kind: Deployment
metadata:
  name: mirakurun
  namespace: epg-station
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: mirakurun
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: epg-station
        app.kubernetes.io/name: mirakurun
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Tokyo
        image: chinachu/mirakurun
        imagePullPolicy: Always
        name: mirakurun
        ports:
        - containerPort: 40772
          protocol: TCP
        - containerPort: 9229
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - SYS_NICE
          privileged: true
        volumeMounts:
        - mountPath: /app-config
          name: config
          readOnly: true
        - mountPath: /dev/bus
          name: bus
        - mountPath: /app-data
          name: app-data
        - mountPath: /opt
          name: opt
      initContainers:
      - command:
        - /bin/sh
        - /app-config/install-recpt1.sh
        image: debian:buster
        name: build-recpt1
        resources: {}
        volumeMounts:
        - mountPath: /app-config
          name: config
          readOnly: true
        - mountPath: /opt
          name: opt
      nodeSelector:
        kubernetes.io/arch: amd64
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: mirakurun
        name: config
      - hostPath:
          path: /dev/bus
          type: Directory
        name: bus
      - name: app-data
        persistentVolumeClaim:
          claimName: mirakurun-app-data
      - name: opt
        persistentVolumeClaim:
          claimName: mirakurun-opt
