apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: epg-station
    app.kubernetes.io/name: mysql
  name: mysql
  namespace: epg-station
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
  type: ClusterIP

